# Generated by Django 4.2.4 on 2023-09-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_rename_members_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="image",
            field=models.ImageField(upload_to="uploads/members"),
        ),
    ]
