# Generated by Django 4.2.4 on 2023-09-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_member_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="mail",
            field=models.EmailField(default="teambarrelay@gmail.com", max_length=254),
        ),
    ]
