# Generated by Django 4.2.4 on 2023-09-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_member_mail"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("subtitle", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="index_slider")),
                ("href", models.CharField(default="index", max_length=100)),
            ],
        ),
    ]
