# Generated by Django 4.2.4 on 2023-09-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_indexslider"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IndexSlider",
            new_name="Index_Slider",
        ),
    ]
