# Generated by Django 4.2.4 on 2023-09-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="source",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
    ]
