# Generated by Django 4.2.4 on 2023-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_source_is_new_source_is_popular"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("user_password", models.CharField(max_length=50)),
            ],
        ),
    ]
