# Generated by Django 4.2.4 on 2023-09-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="lname",
            new_name="confirm_password",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_password",
            new_name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=123123, max_length=50),
            preserve_default=False,
        ),
    ]
