# Generated by Django 4.2.4 on 2023-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_rename_lname_user_confirm_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.IntegerField()),
                ("comment", models.TextField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name="User",
            new_name="UserInfo",
        ),
    ]
