# Generated by Django 4.2.4 on 2023-09-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0014_comment_rename_user_userinfo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="ContactUs",
        ),
    ]
