# Generated by Django 4.2.4 on 2023-09-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0015_rename_comment_contactus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
