# Generated by Django 4.2.4 on 2023-09-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0017_delete_contactus"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "İletişim Mesajı",
                "verbose_name_plural": "İletişim Mesajları",
            },
        ),
    ]
