# Generated by Django 4.2.4 on 2023-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0020_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="grade",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="subject",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
