# Generated by Django 4.2.4 on 2023-09-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0021_source_grade_source_subject_source_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="source",
            old_name="page_number",
            new_name="number_of_page",
        ),
        migrations.RemoveField(
            model_name="source",
            name="source_name",
        ),
        migrations.AddField(
            model_name="source",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="name",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="source",
            name="publisher",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="source",
            name="slug",
            field=models.SlugField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="source",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name="source",
            name="grade",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AlterField(
            model_name="source",
            name="subject",
            field=models.CharField(default="source", max_length=100),
        ),
    ]
