# Generated by Django 4.2.4 on 2023-09-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_rename_name_source_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source',
            new_name='Book',
        ),
    ]
