# Generated by Django 4.2.4 on 2023-09-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_rename_source_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Grade',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='source_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='category_name',
            new_name='grade',
        ),
    ]
