# Generated by Django 4.2.4 on 2023-09-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_rename_category_grade_rename_source_name_book_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitapsec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(null=True)),
                ('original_price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('score', models.FloatField(null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='books')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Kitapsec',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.kitapsec'),
        ),
    ]
