# Generated by Django 4.2.4 on 2023-09-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_kitapsec_book_kitapsec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bkmkitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(null=True)),
                ('original_price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('score', models.FloatField(null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='books')),
            ],
        ),
        migrations.CreateModel(
            name='Isemkitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(null=True)),
                ('original_price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('score', models.FloatField(null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='books')),
            ],
        ),
        migrations.CreateModel(
            name='Islerkitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(null=True)),
                ('original_price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('score', models.FloatField(null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='books')),
            ],
        ),
        migrations.CreateModel(
            name='Kitapsepeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(null=True)),
                ('original_price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('score', models.FloatField(null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='books')),
            ],
        ),
        migrations.CreateModel(
            name='Kitapyurdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(null=True)),
                ('original_price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('score', models.FloatField(null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='books')),
            ],
        ),
        migrations.CreateModel(
            name='Sadecekitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(null=True)),
                ('original_price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('score', models.FloatField(null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='books')),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Kitapsec',
            new_name='kitapsec',
        ),
        migrations.AddField(
            model_name='book',
            name='bkmkitap',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.bkmkitap'),
        ),
        migrations.AddField(
            model_name='book',
            name='isemkitap',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.isemkitap'),
        ),
        migrations.AddField(
            model_name='book',
            name='islerkitap',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.islerkitap'),
        ),
        migrations.AddField(
            model_name='book',
            name='kitapsepeti',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.kitapsepeti'),
        ),
        migrations.AddField(
            model_name='book',
            name='kitapyurdu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.kitapyurdu'),
        ),
        migrations.AddField(
            model_name='book',
            name='sadecekitap',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sadecekitap'),
        ),
    ]
