# Generated by Django 4.2.4 on 2023-09-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainapp",
            "0027_bkmkitap_isemkitap_islerkitap_kitapsepeti_kitapyurdu_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="category",
            new_name="subject",
        ),
    ]
