# Generated by Django 4.2.4 on 2023-09-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0028_rename_category_book_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="page_number",
            new_name="number_of_page",
        ),
    ]
