# Generated by Django 4.2.4 on 2023-09-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0029_rename_page_number_book_number_of_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="is_new",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_popular",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
