# Generated by Django 4.2.4 on 2023-09-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0030_alter_book_is_new_alter_book_is_popular"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="is_new",
        ),
        migrations.RemoveField(
            model_name="book",
            name="is_popular",
        ),
    ]
