# Generated by Django 4.2.4 on 2023-09-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0031_remove_book_is_new_remove_book_is_popular"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bkmkitap",
            table="bkmkitap",
        ),
        migrations.AlterModelTable(
            name="isemkitap",
            table="isemkitap",
        ),
        migrations.AlterModelTable(
            name="islerkitap",
            table="islerkitap",
        ),
        migrations.AlterModelTable(
            name="kitapsec",
            table="kitapsec",
        ),
        migrations.AlterModelTable(
            name="kitapsepeti",
            table="kitapsepeti",
        ),
        migrations.AlterModelTable(
            name="kitapyurdu",
            table="kitapyurdu",
        ),
        migrations.AlterModelTable(
            name="sadecekitap",
            table="sadecekitap",
        ),
    ]
