# Generated by Django 4.2.4 on 2023-09-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0032_alter_bkmkitap_table_alter_isemkitap_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="book",
            table="book",
        ),
    ]
