# Generated by Django 4.2.4 on 2023-09-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0033_alter_book_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="bkmkitap",
            name="grade",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="bkmkitap",
            name="name",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="bkmkitap",
            name="number_of_page",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bkmkitap",
            name="publisher",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="bkmkitap",
            name="subject",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="bkmkitap",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bkmkitap",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name="isemkitap",
            name="grade",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="isemkitap",
            name="name",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="isemkitap",
            name="number_of_page",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="isemkitap",
            name="publisher",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="isemkitap",
            name="subject",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="isemkitap",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="isemkitap",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name="islerkitap",
            name="grade",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="islerkitap",
            name="name",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="islerkitap",
            name="number_of_page",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="islerkitap",
            name="publisher",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="islerkitap",
            name="subject",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="islerkitap",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="islerkitap",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name="kitapsec",
            name="grade",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="kitapsec",
            name="name",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="kitapsec",
            name="number_of_page",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="kitapsec",
            name="publisher",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="kitapsec",
            name="subject",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="kitapsec",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="kitapsec",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name="kitapsepeti",
            name="grade",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="kitapsepeti",
            name="name",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="kitapsepeti",
            name="number_of_page",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="kitapsepeti",
            name="publisher",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="kitapsepeti",
            name="subject",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="kitapsepeti",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="kitapsepeti",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name="kitapyurdu",
            name="grade",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="kitapyurdu",
            name="name",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="kitapyurdu",
            name="number_of_page",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="kitapyurdu",
            name="publisher",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="kitapyurdu",
            name="subject",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="kitapyurdu",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="kitapyurdu",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name="sadecekitap",
            name="grade",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="sadecekitap",
            name="name",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="sadecekitap",
            name="number_of_page",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sadecekitap",
            name="publisher",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="sadecekitap",
            name="subject",
            field=models.CharField(default="source", max_length=100),
        ),
        migrations.AddField(
            model_name="sadecekitap",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sadecekitap",
            name="year",
            field=models.IntegerField(default=2023),
        ),
    ]
