# Generated by Django 4.2.4 on 2023-09-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainapp",
            "0034_bkmkitap_grade_bkmkitap_name_bkmkitap_number_of_page_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bkmkitap",
            name="year",
            field=models.IntegerField(default=2023, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.IntegerField(default=2023, null=True),
        ),
        migrations.AlterField(
            model_name="isemkitap",
            name="year",
            field=models.IntegerField(default=2023, null=True),
        ),
        migrations.AlterField(
            model_name="islerkitap",
            name="year",
            field=models.IntegerField(default=2023, null=True),
        ),
        migrations.AlterField(
            model_name="kitapsec",
            name="year",
            field=models.IntegerField(default=2023, null=True),
        ),
        migrations.AlterField(
            model_name="kitapsepeti",
            name="year",
            field=models.IntegerField(default=2023, null=True),
        ),
        migrations.AlterField(
            model_name="kitapyurdu",
            name="year",
            field=models.IntegerField(default=2023, null=True),
        ),
        migrations.AlterField(
            model_name="sadecekitap",
            name="year",
            field=models.IntegerField(default=2023, null=True),
        ),
    ]
