# Generated by Django 4.2.4 on 2023-09-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0035_alter_bkmkitap_year_alter_book_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bkmkitap",
            name="grade",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="bkmkitap",
            name="link",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="bkmkitap",
            name="name",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="bkmkitap",
            name="publisher",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="bkmkitap",
            name="subject",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="bkmkitap",
            name="type",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="grade",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="book",
            name="subject",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="book",
            name="type",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="isemkitap",
            name="grade",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="isemkitap",
            name="link",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="isemkitap",
            name="name",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="isemkitap",
            name="publisher",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="isemkitap",
            name="subject",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="isemkitap",
            name="type",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="islerkitap",
            name="grade",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="islerkitap",
            name="link",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="islerkitap",
            name="name",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="islerkitap",
            name="publisher",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="islerkitap",
            name="subject",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="islerkitap",
            name="type",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="kitapsec",
            name="grade",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="kitapsec",
            name="link",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="kitapsec",
            name="name",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="kitapsec",
            name="publisher",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="kitapsec",
            name="subject",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="kitapsec",
            name="type",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="kitapsepeti",
            name="grade",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="kitapsepeti",
            name="link",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="kitapsepeti",
            name="name",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="kitapsepeti",
            name="publisher",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="kitapsepeti",
            name="subject",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="kitapsepeti",
            name="type",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="kitapyurdu",
            name="grade",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="kitapyurdu",
            name="link",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="kitapyurdu",
            name="name",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="kitapyurdu",
            name="publisher",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="kitapyurdu",
            name="subject",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="kitapyurdu",
            name="type",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="sadecekitap",
            name="grade",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="sadecekitap",
            name="link",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="sadecekitap",
            name="name",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="sadecekitap",
            name="publisher",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="sadecekitap",
            name="subject",
            field=models.CharField(default="source", max_length=500),
        ),
        migrations.AlterField(
            model_name="sadecekitap",
            name="type",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
