# Generated by Django 4.2.4 on 2023-09-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0036_alter_bkmkitap_grade_alter_bkmkitap_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bkmkitap",
            name="image",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="bkmkitap",
            name="number_of_page",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="number_of_page",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="isemkitap",
            name="image",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="isemkitap",
            name="number_of_page",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="islerkitap",
            name="image",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="islerkitap",
            name="number_of_page",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="kitapsec",
            name="image",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="kitapsec",
            name="number_of_page",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="kitapsepeti",
            name="image",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="kitapsepeti",
            name="number_of_page",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="kitapyurdu",
            name="image",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="kitapyurdu",
            name="number_of_page",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="sadecekitap",
            name="image",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="sadecekitap",
            name="number_of_page",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
