# Generated by Django 4.2.4 on 2024-06-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="members")),
                (
                    "mail",
                    models.EmailField(default="teambarrelay@gmail.com", max_length=254),
                ),
            ],
        ),
    ]
