# Generated by Django 5.0.6 on 2024-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinav_turu', models.CharField(max_length=100)),
                ('ders', models.CharField(max_length=100)),
                ('kitap_adi', models.CharField(max_length=255)),
                ('yazar_adi', models.CharField(max_length=255)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yayincilik', models.CharField(max_length=255)),
                ('sayfa_sayisi', models.CharField(max_length=100)),
                ('yayin_tarihi', models.DateField()),
            ],
        ),
    ]
