# Generated by Django 5.0.6 on 2024-09-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='yayin_tarihi',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
