# Generated by Django 5.0.6 on 2024-09-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_alter_kitap_fiyat_alter_kitap_yayin_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='kapak_foto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
