# Generated by Django 5.0.6 on 2024-09-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_kitap_kapak_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='puan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='sayfa_sayisi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
