# Generated by Django 5.0.6 on 2024-09-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_kitap_puan_alter_kitap_sayfa_sayisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='puan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
