# Generated by Django 5.0.6 on 2024-09-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_alter_kitap_puan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='sayfa_sayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
