# Generated by Django 5.0.6 on 2024-09-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_remove_kitap_puan_alter_kitap_yayin_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='puan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
