# Generated by Django 5.0.6 on 2024-09-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_kitap_puan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='puan',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
