# Generated by Django 4.2.4 on 2024-10-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0009_alter_kitap_puan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kitap",
            name="kapak_foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/img/kapak_foto/"
            ),
        ),
    ]
